### ISSUE TITLE
Specification for Adjustable Parameters

### ISSUE THREAD

**Issue by jlaura** [sminster/csm#15]
Do the adjustable parameters (getters/setters in the Geometric Model) conform to any specification or are they defined implementation by implementation? 

For example, [here is a LineScan sensor implementation with 16 parameters defined](https://github.com/USGS-Astrogeology/usgscsm/blob/dev/src/UsgsAstroLsSensorModel.cpp#L41).

We are wondering how a SET might make use of the adjustable parameters, say to performa bundle adjustment, if the names and ordering of the adjustable parameters is not explicitly defined by some specification.

**Comment by johnpdpkarp** [comment]
The adjustable parameters can freely be defined for any model.

Typically bundle adjustment makes use of the parameters in conjunction to their partial derivatives.   Since the partials are typically with respect to the “detected space”, they are not defined on GeometricModel.

They are, howver defined on RasterGM, which I would assume your Line Scanner model would derive from.

The partial derivatives of the parameters with respect to raster coordinates and the parameter covariances, along with the adjusted value of the parameters all contribute to the bundle adjustment.

If you have specific questions on Bundle Adjustment, feel free to contact me directly.

John Karp
Harris Corporation
jkarp01@harris.com<mailto:jkarp01@harris.com>
(321) 984-5708
